### ISSUE TITLE
znx-gui Master does not work

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx-gui#12]
**Describe the bug**
The resulting binary from the master branch does not work.

**To Reproduce**
1. Download AppImage of `znx-gui`.
2. Execute and perform an action.
3. `znx-gui` displays, "Operation failed!".

**Expected behavior**
`znx-gui` performs the selected action.

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04.3

**Comment by UriHerrera** [comment]
I created a branch `master-test`, and I have fixed a couple of problems that znx-gui had, but there's a new problem now.

Confirmation of the commands of znx isn't working. Znx fails with the error `znx: Error: Unkown command -y`.

**Comment by luis-lavaire** [comment]
Could you create a PR against the `development` branch?

**Comment by luis-lavaire** [comment]
@UriHerrera, this was solved, right?

**Comment by UriHerrera** [comment]
@luis-lavaire No, it's not working.

**Comment by UriHerrera** [comment]
znx-gui master works.
