### ISSUE TITLE
Add progressbar when ISO is being deployed from a remote URL

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx-gui#4]
Currently, there's no way to know the status of the download other than watching network activity.

https://scottferguson.com.au/community/FOSS/kdialog.html
https://mostlylinux.wordpress.com/bashscripting/kdialog/

**Comment by luis-lavaire** [comment]
Unfortunately, displaying a progressbar requires processing the standard output stream of `axel` or `zsync` (depending on wether it's a deployment or an update) from within the script; which is obnoxious. Notification dialogs are used to inform the user about the progress of the deployment.
