### ISSUE TITLE
Use notification instead of window to notify user of success or errors 

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx-gui#5]
The windows get overlapped since the user has to click the first window to dismiss it, and the success or error window appears below it.

The notification is known as a passive popup.

https://scottferguson.com.au/community/FOSS/kdialog.html
https://mostlylinux.wordpress.com/bashscripting/kdialog/

**Comment by luis-lavaire** [comment]
Solved in 9ade029.
