### ISSUE TITLE
znx-gui AppImage doesn't run

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/znx-gui#7]
It looks like the reason why the AppImage doesn't work is that dependencies are missing during the build of the file.

**Comment by UriHerrera** [comment]
Further testing. I have added more dependencies to the build script; however, the resulting AppImage doesn't run.

```
uri@host:~/Downloads$ ./znx-gui_master-x86_64.AppImage 
+ alias ui=kdialog --title='ZNX_GUI'
+ CMDS=init restore-esp deploy update revert remove clean reset stats
+ :
+ select_command
+ kdialog --title=ZNX_GUI --combobox Command to run: init restore-esp deploy update revert remove clean reset stats
Segmentation fault
+ COMMAND=
+ [ 0 -gt 0 ]
+ error Operation cancelled.
+ kdialog --title=ZNX_GUI --error Operation cancelled.
Segmentation fault
+ exit 1
```

**Comment by luis-lavaire** [comment]
> After testing a bit more, I changed the Docker image that Travis uses to build the AppImage, and the resulting file works in Nitrux; however, it doesn't work in Ubuntu, but now it gives a different error that says that it's missing a library libqtdbus4 .

I'm running Manjaro 18.0.4, and I'm getting the same error.

**Comment by luis-lavaire** [comment]
We should try to build it on a Manjaro-based environment. To support other OS's, we could provide a `PKGBUILD`.

**Comment by luis-lavaire** [comment]
It was working when built in xenial, right?

**Comment by UriHerrera** [comment]
No, it didn't work.

**Comment by luis-lavaire** [comment]
It worked for me at some point. :thinking:
Did it never work for you?

**Comment by UriHerrera** [comment]
I don't remember, but I don't think that it did.

**Comment by UriHerrera** [comment]
![VirtualBox_Ubuntu_04_06_2019_20_01_56](https://user-images.githubusercontent.com/3053525/58923079-a9818480-8703-11e9-9f43-a2b70fc3e93f.png)

Building the AppImage with 16.04 doesn't make any difference; it complains that kdialog can't find the library even though it is there.

**Comment by luis-lavaire** [comment]
If this is the case, we are facing an issue with the AppImage format, not with `znx` and `znx-gui` themselves.

**Comment by UriHerrera** [comment]
Can confirm that https://github.com/Nitrux/znx-gui/commit/ee247a368af49642e1f93c5ab766d8ca98c806bb works.
